name: exoteric
favicon: null
layout_spectrum: 0.30014606029726565
typography_spectrum: 0.6414138744585216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5822380217723548
  lightness: 0.7763995993882418
  saturation: 0.6108069778420031
  rhythmicContrast: 0.830635612597689
purpose: []
